### ISSUE TITLE
Execution in the Netbeans IDE failed

### ISSUE THREAD

**Issue by orat** [MobMonRob/MathExprParserStudien#9]
Exception in thread "main" java.lang.IllegalAccessError: class de.dhbw.karlsruhe.dsl.Main (in unnamed module @0x69a3d1d) cannot access class com.oracle.truffle.api.RootCallTarget (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api to unnamed module @0x69a3d1d
	at de.dhbw.karlsruhe.dsl.Main.inputFunction(Main.java:25)
	at de.dhbw.karlsruhe.dsl.Main.main(Main.java:15)
Command execution failed.

**Comment by orat** [comment]
When the Java module system is available (>= JDK 9) then only classes are accessible that are exported to the unnamed module of the captured class loader.

**Comment by orat** [comment]
fixed by adding export properties
